In [97]:
import pandas as pd

In [115]:
HBV_df=pd.read_csv(r"C:\Users\kanka\Downloads\IHME-GBD_2021_DATA-5b8c75b2-1\IHME-GBD_2021_DATA-5b8c75b2-1.csv",sep=',')

In [119]:
HBV_df=HBV_df.head(25)
HBV_df

,measure_id,measure_name,location_id,location_name,sex_id,sex_name,age_id,age_name,cause_id,cause_name,metric_id,metric_name,year,val,upper,lower
0,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2016,1248.833323,1662.893581,823.730925
1,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2016,0.009743,0.012337,0.006691
2,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2016,7.384998,9.833551,4.871147
3,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2021,865.690929,1280.041697,565.167275
4,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2021,0.009363,0.013269,0.006599
5,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2021,6.523653,9.646108,4.258974
6,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2021,1037.852588,1496.728303,709.517663
7,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2021,0.011225,0.015110,0.008343
8,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2021,7.821025,11.279010,5.346767
9,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2021,730.074363,1011.352112,509.338396
10,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2021,0.009892,0.012831,0.007402
11,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2021,13.312480,18.441416,9.287488
12,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,1,Number,2021,96.819973,185.519742,35.359411
13,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,2,Percent,2021,0.000138,0.000262,0.000053
14,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,3,Rate,2021,0.107557,0.206092,0.039280
15,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2021,1667.558554,2264.209720,1147.280991
16,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2021,0.007974,0.010094,0.005973
17,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2021,5.985091,8.126552,4.117745
18,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2016,1535.326787,1964.847872,1102.382723
19,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2016,0.011972,0.014582,0.009348
20,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2016,9.079182,11.619163,6.518960
21,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2016,126.590735,187.662905,88.082791
22,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2016,0.006919,0.010221,0.004971
23,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2016,5.708636,8.462698,3.972112
24,1,Deaths,194,Lesotho,3,Both,22,All ages,402,Acute hepatitis B,1,Number,2016,27.601377,41.506392,17.612427

In [121]:
HBV_df.index=range(1,26)
HBV_df

,measure_id,measure_name,location_id,location_name,sex_id,sex_name,age_id,age_name,cause_id,cause_name,metric_id,metric_name,year,val,upper,lower
1,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2016,1248.833323,1662.893581,823.730925
2,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2016,0.009743,0.012337,0.006691
3,1,Deaths,191,Zambia,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2016,7.384998,9.833551,4.871147
4,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2021,865.690929,1280.041697,565.167275
5,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2021,0.009363,0.013269,0.006599
6,1,Deaths,185,Rwanda,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2021,6.523653,9.646108,4.258974
7,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2021,1037.852588,1496.728303,709.517663
8,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2021,0.011225,0.015110,0.008343
9,1,Deaths,185,Rwanda,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2021,7.821025,11.279010,5.346767
10,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2021,730.074363,1011.352112,509.338396
11,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2021,0.009892,0.012831,0.007402
12,1,Deaths,169,Central African Republic,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2021,13.312480,18.441416,9.287488
13,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,1,Number,2021,96.819973,185.519742,35.359411
14,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,2,Percent,2021,0.000138,0.000262,0.000053
15,1,Deaths,171,Democratic Republic of the Congo,3,Both,22,All ages,402,Acute hepatitis B,3,Rate,2021,0.107557,0.206092,0.039280
16,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,1,Number,2021,1667.558554,2264.209720,1147.280991
17,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,2,Percent,2021,0.007974,0.010094,0.005973
18,1,Deaths,205,Côte d'Ivoire,3,Both,22,All ages,522,Chronic hepatitis B including cirrhosis,3,Rate,2021,5.985091,8.126552,4.117745
19,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2016,1535.326787,1964.847872,1102.382723
20,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2016,0.011972,0.014582,0.009348
21,1,Deaths,191,Zambia,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2016,9.079182,11.619163,6.518960
22,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,1,Number,2016,126.590735,187.662905,88.082791
23,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,2,Percent,2016,0.006919,0.010221,0.004971
24,1,Deaths,193,Botswana,3,Both,22,All ages,1026,Total burden related to hepatitis B,3,Rate,2016,5.708636,8.462698,3.972112
25,1,Deaths,194,Lesotho,3,Both,22,All ages,402,Acute hepatitis B,1,Number,2016,27.601377,41.506392,17.612427

In [131]:
HBV_df=HBV_df.drop(columns=["measure_id","location_id","sex_id","sex_name","age_id","age_name","cause_id","cause_name","metric_id","metric_name","upper","lower"])

In [133]:
HBV_df=HBV_df.drop(columns="measure_name")
HBV_df

                       location_name  year          val
1                             Zambia  2016  1248.833323
2                             Zambia  2016     0.009743
3                             Zambia  2016     7.384998
4                             Rwanda  2021   865.690929
5                             Rwanda  2021     0.009363
6                             Rwanda  2021     6.523653
7                             Rwanda  2021  1037.852588
8                             Rwanda  2021     0.011225
9                             Rwanda  2021     7.821025
10          Central African Republic  2021   730.074363
11          Central African Republic  2021     0.009892
12          Central African Republic  2021    13.312480
13  Democratic Republic of the Congo  2021    96.819973
14  Democratic Republic of the Congo  2021     0.000138
15  Democratic Republic of the Congo  2021     0.107557
16                     Côte d'Ivoire  2021  1667.558554
17                     Côte d'Ivoire  2021     0.007974
18                     Côte d'Ivoire  2021     5.985091
19                            Zambia  2016  1535.326787
20                            Zambia  2016     0.011972
21                            Zambia  2016     9.079182
22                          Botswana  2016   126.590735
23                          Botswana  2016     0.006919
24                          Botswana  2016     5.708636
25                           Lesotho  2016    27.601377

In [143]:
HBV_df= HBV_df.rename(columns={"location_name": "Country/Region", "val": "Annual deaths", "year": "Year of estimate"})
HBV_df

                      Country/Region  Year of estimate  Annual deaths
1                             Zambia              2016    1248.833323
2                             Zambia              2016       0.009743
3                             Zambia              2016       7.384998
4                             Rwanda              2021     865.690929
5                             Rwanda              2021       0.009363
6                             Rwanda              2021       6.523653
7                             Rwanda              2021    1037.852588
8                             Rwanda              2021       0.011225
9                             Rwanda              2021       7.821025
10          Central African Republic              2021     730.074363
11          Central African Republic              2021       0.009892
12          Central African Republic              2021      13.312480
13  Democratic Republic of the Congo              2021      96.819973
14  Democratic Republic of the Congo              2021       0.000138
15  Democratic Republic of the Congo              2021       0.107557
16                     Côte d'Ivoire              2021    1667.558554
17                     Côte d'Ivoire              2021       0.007974
18                     Côte d'Ivoire              2021       5.985091
19                            Zambia              2016    1535.326787
20                            Zambia              2016       0.011972
21                            Zambia              2016       9.079182
22                          Botswana              2016     126.590735
23                          Botswana              2016       0.006919
24                          Botswana              2016       5.708636
25                           Lesotho              2016      27.601377

In [145]:
HBV_df['Annual deaths'] =HBV_df['Annual deaths'].round(0).astype(int)
HBV_df

                      Country/Region  Year of estimate  Annual deaths
1                             Zambia              2016           1249
2                             Zambia              2016              0
3                             Zambia              2016              7
4                             Rwanda              2021            866
5                             Rwanda              2021              0
6                             Rwanda              2021              7
7                             Rwanda              2021           1038
8                             Rwanda              2021              0
9                             Rwanda              2021              8
10          Central African Republic              2021            730
11          Central African Republic              2021              0
12          Central African Republic              2021             13
13  Democratic Republic of the Congo              2021             97
14  Democratic Republic of the Congo              2021              0
15  Democratic Republic of the Congo              2021              0
16                     Côte d'Ivoire              2021           1668
17                     Côte d'Ivoire              2021              0
18                     Côte d'Ivoire              2021              6
19                            Zambia              2016           1535
20                            Zambia              2016              0
21                            Zambia              2016              9
22                          Botswana              2016            127
23                          Botswana              2016              0
24                          Botswana              2016              6
25                           Lesotho              2016             28

In [147]:
HBV_df=HBV_df.groupby(['Country/Region', 'Year of estimate'], as_index=False)['Annual deaths'].sum()
HBV_df

                     Country/Region  Year of estimate  Annual deaths
0                          Botswana              2016            133
1          Central African Republic              2021            743
2                     Côte d'Ivoire              2021           1674
3  Democratic Republic of the Congo              2021             97
4                           Lesotho              2016             28
5                            Rwanda              2021           1919
6                            Zambia              2016           2800

In [175]:
HBV_df.index=range(1,8)
HBV_df=HBV_df.drop(columns="index")
HBV_df

                     Country/Region  Year of estimate  Annual deaths
1                          Botswana              2016            133
2          Central African Republic              2021            743
3                     Côte d'Ivoire              2021           1674
4  Democratic Republic of the Congo              2021             97
5                           Lesotho              2016             28
6                            Rwanda              2021           1919
7                            Zambia              2016           2800

In [155]:
HIV_df=pd.read_csv(r"C:\Users\kanka\Downloads\archive\hiv_prevalence.csv",sep=';', encoding='latin1')

In [157]:
HIV_df=HIV_df.head(25)
HIV_df

,"Country/Region,",Adult prevalence,Number of people,Annual deaths,Year of estimate
0,NaN,"of HIV/AIDS,","with HIV/AIDS,","from HIV/AIDS,",NaN
1,Eswatini,28.30%,"240,000","3,000",2024
2,Lesotho,24.10%,"403,000","5,380",2024
3,Botswana,22.60%,"398,500","5,240",2024
4,Zimbabwe,22.10%,"1,660,000","25,600",2024
5,South Africa,14%,"9,230,000","77,000",2024
6,Namibia,13.20%,"219,330","3,880",2024
7,Zambia,12.50%,"1,550,000","20,000",2023
8,Mozambique,12.65%,"2,485,000","59,100",2024
9,Malawi,11.40%,"1,642,570","15,270",2024
10,Equatorial Guinea,7.66%,"74,165","2,400",2024
11,Tanzania,5.45%,"2,550,000","33,000",2024
12,Kenya,5.10%,"1,710,000","24,000",2023
13,Uganda,5%,"1,590,000","23,300",2023
14,Togo,5.20%,"220,440","6,600",2024
15,Cameroon,4%,"530,000","14,600",2023
16,Gabon,3.90%,"59,000","1,500",2023
17,Central African Republic,4%,"126,200","4,400",2024
18,Guinea-Bissau,3.65%,"42,000","2,200",2023
19,"Congo, Republic of the",3.77%,"110,840","6,700",2024
20,Barbados,3.10%,"4,400",-,2023
21,Rwanda,2.90%,"230,000","2,800",2016
22,Côte d'Ivoire,2.70%,"430,000","13,000",2016
23,South Sudan,2.40%,"190,000","9,100",2016
24,"Gambia, The",2.40%,"31,000","1,540",2023

In [159]:
HIV_df.index=range(1,26)
HIV_df

,"Country/Region,",Adult prevalence,Number of people,Annual deaths,Year of estimate
1,NaN,"of HIV/AIDS,","with HIV/AIDS,","from HIV/AIDS,",NaN
2,Eswatini,28.30%,"240,000","3,000",2024
3,Lesotho,24.10%,"403,000","5,380",2024
4,Botswana,22.60%,"398,500","5,240",2024
5,Zimbabwe,22.10%,"1,660,000","25,600",2024
6,South Africa,14%,"9,230,000","77,000",2024
7,Namibia,13.20%,"219,330","3,880",2024
8,Zambia,12.50%,"1,550,000","20,000",2023
9,Mozambique,12.65%,"2,485,000","59,100",2024
10,Malawi,11.40%,"1,642,570","15,270",2024
11,Equatorial Guinea,7.66%,"74,165","2,400",2024
12,Tanzania,5.45%,"2,550,000","33,000",2024
13,Kenya,5.10%,"1,710,000","24,000",2023
14,Uganda,5%,"1,590,000","23,300",2023
15,Togo,5.20%,"220,440","6,600",2024
16,Cameroon,4%,"530,000","14,600",2023
17,Gabon,3.90%,"59,000","1,500",2023
18,Central African Republic,4%,"126,200","4,400",2024
19,Guinea-Bissau,3.65%,"42,000","2,200",2023
20,"Congo, Republic of the",3.77%,"110,840","6,700",2024
21,Barbados,3.10%,"4,400",-,2023
22,Rwanda,2.90%,"230,000","2,800",2016
23,Côte d'Ivoire,2.70%,"430,000","13,000",2016
24,South Sudan,2.40%,"190,000","9,100",2016
25,"Gambia, The",2.40%,"31,000","1,540",2023

In [165]:
HIV_df=HIV_df.drop(columns=["Adult prevalence","Number of people"])

In [167]:
HIV_df

              Country/Region,   Annual deaths Year of estimate
1                         NaN  from HIV/AIDS,              NaN
2                    Eswatini           3,000             2024
3                     Lesotho           5,380             2024
4                    Botswana           5,240             2024
5                    Zimbabwe          25,600             2024
6                South Africa          77,000             2024
7                     Namibia           3,880             2024
8                      Zambia          20,000             2023
9                  Mozambique          59,100             2024
10                     Malawi          15,270             2024
11          Equatorial Guinea           2,400             2024
12                   Tanzania          33,000             2024
13                      Kenya          24,000             2023
14                     Uganda          23,300             2023
15                       Togo           6,600             2024
16                   Cameroon          14,600             2023
17                      Gabon           1,500             2023
18   Central African Republic           4,400             2024
19              Guinea-Bissau           2,200             2023
20     Congo, Republic of the           6,700             2024
21                   Barbados               -             2023
22                     Rwanda           2,800             2016
23              Côte d'Ivoire          13,000             2016
24                South Sudan           9,100             2016
25                Gambia, The           1,540             2023

In [169]:
HIV_df=HIV_df.rename(columns={'Country/Region,':'Country/Region'})
HIV_df

               Country/Region   Annual deaths Year of estimate
1                         NaN  from HIV/AIDS,              NaN
2                    Eswatini           3,000             2024
3                     Lesotho           5,380             2024
4                    Botswana           5,240             2024
5                    Zimbabwe          25,600             2024
6                South Africa          77,000             2024
7                     Namibia           3,880             2024
8                      Zambia          20,000             2023
9                  Mozambique          59,100             2024
10                     Malawi          15,270             2024
11          Equatorial Guinea           2,400             2024
12                   Tanzania          33,000             2024
13                      Kenya          24,000             2023
14                     Uganda          23,300             2023
15                       Togo           6,600             2024
16                   Cameroon          14,600             2023
17                      Gabon           1,500             2023
18   Central African Republic           4,400             2024
19              Guinea-Bissau           2,200             2023
20     Congo, Republic of the           6,700             2024
21                   Barbados               -             2023
22                     Rwanda           2,800             2016
23              Côte d'Ivoire          13,000             2016
24                South Sudan           9,100             2016
25                Gambia, The           1,540             2023

In [203]:
HIV_df = HIV_df.drop(index=[1, 20])

In [183]:
HIV_df.index=range(1,24)
HIV_df

               Country/Region Annual deaths Year of estimate
1                    Eswatini         3,000             2024
2                     Lesotho         5,380             2024
3                    Botswana         5,240             2024
4                    Zimbabwe        25,600             2024
5                South Africa        77,000             2024
6                     Namibia         3,880             2024
7                      Zambia        20,000             2023
8                  Mozambique        59,100             2024
9                      Malawi        15,270             2024
10          Equatorial Guinea         2,400             2024
11                   Tanzania        33,000             2024
12                      Kenya        24,000             2023
13                     Uganda        23,300             2023
14                       Togo         6,600             2024
15                   Cameroon        14,600             2023
16                      Gabon         1,500             2023
17   Central African Republic         4,400             2024
18              Guinea-Bissau         2,200             2023
19     Congo, Republic of the         6,700             2024
20                     Rwanda         2,800             2016
21              Côte d'Ivoire        13,000             2016
22                South Sudan         9,100             2016
23                Gambia, The         1,540             2023

In [185]:
HBV_df.to_csv("HBV_clean.csv", index=False)
HIV_df.to_csv("HIV_clean.csv", index=False)

In [3]:
import pandas as pd

In [5]:
hiv_df=pd.read_csv("HIV_clean.csv")
hbv_df=pd.read_csv("HBV_clean.csv")

In [7]:
merged_df=pd.merge(hiv_df,hbv_df,on=["Country/Region","Year of estimate"],suffixes=("_HIV","_HBV"),how="outer")
merged_df

,Country/Region,Annual deaths_HIV,Year of estimate,Annual deaths_HBV
0,Botswana,NaN,2016,133.0
1,Central African Republic,NaN,2021,743.0
2,Côte d'Ivoire,NaN,2021,1674.0
3,Democratic Republic of the Congo,NaN,2021,97.0
4,Lesotho,NaN,2016,28.0
5,Rwanda,NaN,2021,1919.0
6,Zambia,NaN,2016,2800.0
7,Botswana,"5,240",2024,NaN
8,Cameroon,"14,600",2023,NaN
9,Central African Republic,"4,400",2024,NaN
10,"Congo, Republic of the","6,700",2024,NaN
11,Côte d'Ivoire,"13,000",2016,NaN
12,Equatorial Guinea,"2,400",2024,NaN
13,Eswatini,"3,000",2024,NaN
14,Gabon,"1,500",2023,NaN
15,"Gambia, The","1,540",2023,NaN
16,Guinea-Bissau,"2,200",2023,NaN
17,Kenya,"24,000",2023,NaN
18,Lesotho,"5,380",2024,NaN
19,Malawi,"15,270",2024,NaN
20,Mozambique,"59,100",2024,NaN
21,Namibia,"3,880",2024,NaN
22,Rwanda,"2,800",2016,NaN
23,South Africa,"77,000",2024,NaN
24,South Sudan,"9,100",2016,NaN
25,Tanzania,"33,000",2024,NaN
26,Togo,"6,600",2024,NaN
27,Uganda,"23,300",2023,NaN
28,Zambia,"20,000",2023,NaN
29,Zimbabwe,"25,600",2024,NaN

In [9]:
merged_df['Year of estimate']=pd.to_numeric(merged_df['Year of estimate'],errors='coerce')

In [11]:
merged_df=merged_df.sort_values(by="Year of estimate")
merged_df

,Country/Region,Annual deaths_HIV,Year of estimate,Annual deaths_HBV
0,Botswana,NaN,2016,133.0
4,Lesotho,NaN,2016,28.0
6,Zambia,NaN,2016,2800.0
24,South Sudan,"9,100",2016,NaN
22,Rwanda,"2,800",2016,NaN
11,Côte d'Ivoire,"13,000",2016,NaN
1,Central African Republic,NaN,2021,743.0
2,Côte d'Ivoire,NaN,2021,1674.0
3,Democratic Republic of the Congo,NaN,2021,97.0
5,Rwanda,NaN,2021,1919.0
27,Uganda,"23,300",2023,NaN
17,Kenya,"24,000",2023,NaN
16,Guinea-Bissau,"2,200",2023,NaN
15,"Gambia, The","1,540",2023,NaN
14,Gabon,"1,500",2023,NaN
8,Cameroon,"14,600",2023,NaN
28,Zambia,"20,000",2023,NaN
13,Eswatini,"3,000",2024,NaN
12,Equatorial Guinea,"2,400",2024,NaN
10,"Congo, Republic of the","6,700",2024,NaN
18,Lesotho,"5,380",2024,NaN
19,Malawi,"15,270",2024,NaN
20,Mozambique,"59,100",2024,NaN
21,Namibia,"3,880",2024,NaN
9,Central African Republic,"4,400",2024,NaN
23,South Africa,"77,000",2024,NaN
25,Tanzania,"33,000",2024,NaN
26,Togo,"6,600",2024,NaN
7,Botswana,"5,240",2024,NaN
29,Zimbabwe,"25,600",2024,NaN

In [13]:
merged_df=merged_df[["Country/Region","Year of estimate","Annual deaths_HIV","Annual deaths_HBV"]]
merged_df

,Country/Region,Year of estimate,Annual deaths_HIV,Annual deaths_HBV
0,Botswana,2016,NaN,133.0
4,Lesotho,2016,NaN,28.0
6,Zambia,2016,NaN,2800.0
24,South Sudan,2016,"9,100",NaN
22,Rwanda,2016,"2,800",NaN
11,Côte d'Ivoire,2016,"13,000",NaN
1,Central African Republic,2021,NaN,743.0
2,Côte d'Ivoire,2021,NaN,1674.0
3,Democratic Republic of the Congo,2021,NaN,97.0
5,Rwanda,2021,NaN,1919.0
27,Uganda,2023,"23,300",NaN
17,Kenya,2023,"24,000",NaN
16,Guinea-Bissau,2023,"2,200",NaN
15,"Gambia, The",2023,"1,540",NaN
14,Gabon,2023,"1,500",NaN
8,Cameroon,2023,"14,600",NaN
28,Zambia,2023,"20,000",NaN
13,Eswatini,2024,"3,000",NaN
12,Equatorial Guinea,2024,"2,400",NaN
10,"Congo, Republic of the",2024,"6,700",NaN
18,Lesotho,2024,"5,380",NaN
19,Malawi,2024,"15,270",NaN
20,Mozambique,2024,"59,100",NaN
21,Namibia,2024,"3,880",NaN
9,Central African Republic,2024,"4,400",NaN
23,South Africa,2024,"77,000",NaN
25,Tanzania,2024,"33,000",NaN
26,Togo,2024,"6,600",NaN
7,Botswana,2024,"5,240",NaN
29,Zimbabwe,2024,"25,600",NaN

In [17]:
merged_df=merged_df.reset_index(drop=True)
merged_df

,Country/Region,Year of estimate,Annual deaths_HIV,Annual deaths_HBV
0,Botswana,2016,NaN,133.0
1,Lesotho,2016,NaN,28.0
2,Zambia,2016,NaN,2800.0
3,South Sudan,2016,"9,100",NaN
4,Rwanda,2016,"2,800",NaN
5,Côte d'Ivoire,2016,"13,000",NaN
6,Central African Republic,2021,NaN,743.0
7,Côte d'Ivoire,2021,NaN,1674.0
8,Democratic Republic of the Congo,2021,NaN,97.0
9,Rwanda,2021,NaN,1919.0
10,Uganda,2023,"23,300",NaN
11,Kenya,2023,"24,000",NaN
12,Guinea-Bissau,2023,"2,200",NaN
13,"Gambia, The",2023,"1,540",NaN
14,Gabon,2023,"1,500",NaN
15,Cameroon,2023,"14,600",NaN
16,Zambia,2023,"20,000",NaN
17,Eswatini,2024,"3,000",NaN
18,Equatorial Guinea,2024,"2,400",NaN
19,"Congo, Republic of the",2024,"6,700",NaN
20,Lesotho,2024,"5,380",NaN
21,Malawi,2024,"15,270",NaN
22,Mozambique,2024,"59,100",NaN
23,Namibia,2024,"3,880",NaN
24,Central African Republic,2024,"4,400",NaN
25,South Africa,2024,"77,000",NaN
26,Tanzania,2024,"33,000",NaN
27,Togo,2024,"6,600",NaN
28,Botswana,2024,"5,240",NaN
29,Zimbabwe,2024,"25,600",NaN

In [19]:
merged_df.index=range(1,31)

In [21]:
merged_df

,Country/Region,Year of estimate,Annual deaths_HIV,Annual deaths_HBV
1,Botswana,2016,NaN,133.0
2,Lesotho,2016,NaN,28.0
3,Zambia,2016,NaN,2800.0
4,South Sudan,2016,"9,100",NaN
5,Rwanda,2016,"2,800",NaN
6,Côte d'Ivoire,2016,"13,000",NaN
7,Central African Republic,2021,NaN,743.0
8,Côte d'Ivoire,2021,NaN,1674.0
9,Democratic Republic of the Congo,2021,NaN,97.0
10,Rwanda,2021,NaN,1919.0
11,Uganda,2023,"23,300",NaN
12,Kenya,2023,"24,000",NaN
13,Guinea-Bissau,2023,"2,200",NaN
14,"Gambia, The",2023,"1,540",NaN
15,Gabon,2023,"1,500",NaN
16,Cameroon,2023,"14,600",NaN
17,Zambia,2023,"20,000",NaN
18,Eswatini,2024,"3,000",NaN
19,Equatorial Guinea,2024,"2,400",NaN
20,"Congo, Republic of the",2024,"6,700",NaN
21,Lesotho,2024,"5,380",NaN
22,Malawi,2024,"15,270",NaN
23,Mozambique,2024,"59,100",NaN
24,Namibia,2024,"3,880",NaN
25,Central African Republic,2024,"4,400",NaN
26,South Africa,2024,"77,000",NaN
27,Tanzania,2024,"33,000",NaN
28,Togo,2024,"6,600",NaN
29,Botswana,2024,"5,240",NaN
30,Zimbabwe,2024,"25,600",NaN

In [23]:
merged_df=merged_df.fillna(0)
merged_df

,Country/Region,Year of estimate,Annual deaths_HIV,Annual deaths_HBV
1,Botswana,2016,0,133.0
2,Lesotho,2016,0,28.0
3,Zambia,2016,0,2800.0
4,South Sudan,2016,"9,100",0.0
5,Rwanda,2016,"2,800",0.0
6,Côte d'Ivoire,2016,"13,000",0.0
7,Central African Republic,2021,0,743.0
8,Côte d'Ivoire,2021,0,1674.0
9,Democratic Republic of the Congo,2021,0,97.0
10,Rwanda,2021,0,1919.0
11,Uganda,2023,"23,300",0.0
12,Kenya,2023,"24,000",0.0
13,Guinea-Bissau,2023,"2,200",0.0
14,"Gambia, The",2023,"1,540",0.0
15,Gabon,2023,"1,500",0.0
16,Cameroon,2023,"14,600",0.0
17,Zambia,2023,"20,000",0.0
18,Eswatini,2024,"3,000",0.0
19,Equatorial Guinea,2024,"2,400",0.0
20,"Congo, Republic of the",2024,"6,700",0.0
21,Lesotho,2024,"5,380",0.0
22,Malawi,2024,"15,270",0.0
23,Mozambique,2024,"59,100",0.0
24,Namibia,2024,"3,880",0.0
25,Central African Republic,2024,"4,400",0.0
26,South Africa,2024,"77,000",0.0
27,Tanzania,2024,"33,000",0.0
28,Togo,2024,"6,600",0.0
29,Botswana,2024,"5,240",0.0
30,Zimbabwe,2024,"25,600",0.0

In [29]:
merged_df["Annual deaths_HBV"]=merged_df["Annual deaths_HBV"].astype(int)

In [33]:
print("Final sorted and cleaned merged dataset is:\n")
merged_df

Final sorted and cleaned merged dataset is:

,Country/Region,Year of estimate,Annual deaths_HIV,Annual deaths_HBV
1,Botswana,2016,0,133
2,Lesotho,2016,0,28
3,Zambia,2016,0,2800
4,South Sudan,2016,"9,100",0
5,Rwanda,2016,"2,800",0
6,Côte d'Ivoire,2016,"13,000",0
7,Central African Republic,2021,0,743
8,Côte d'Ivoire,2021,0,1674
9,Democratic Republic of the Congo,2021,0,97
10,Rwanda,2021,0,1919
11,Uganda,2023,"23,300",0
12,Kenya,2023,"24,000",0
13,Guinea-Bissau,2023,"2,200",0
14,"Gambia, The",2023,"1,540",0
15,Gabon,2023,"1,500",0
16,Cameroon,2023,"14,600",0
17,Zambia,2023,"20,000",0
18,Eswatini,2024,"3,000",0
19,Equatorial Guinea,2024,"2,400",0
20,"Congo, Republic of the",2024,"6,700",0
21,Lesotho,2024,"5,380",0
22,Malawi,2024,"15,270",0
23,Mozambique,2024,"59,100",0
24,Namibia,2024,"3,880",0
25,Central African Republic,2024,"4,400",0
26,South Africa,2024,"77,000",0
27,Tanzania,2024,"33,000",0
28,Togo,2024,"6,600",0
29,Botswana,2024,"5,240",0
30,Zimbabwe,2024,"25,600",0